import type { Metadata } from "next";
import { Athiti, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import HeroPage from "./hero/page";

const athiti = Athiti({
  variable: "--font-athiti",
  subsets: ["latin"],
  weight: ['200' , '300' , '400', '500', '600' ,'700']
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${athiti.variable} ${geistMono.variable} antialiased`}
      >
         <HeroPage />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
